// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Fredrik Hammarström

// Durable-session backend: drive tmux as a persistence layer. Each terminal becomes a tmux
// *client* attached to a long-lived *session* on a private tmux server. The server detaches
// from whatever launched it, so it outlives the app — quit/reload only detaches clients, and
// the next launch reattaches. No electron imports (stays portable; used by main + pty-host).

import { execFile } from 'node:child_process'
import { promisify } from 'node:util'
import { TMUX_SOCKET } from '@shared/tmux'

const pexec = promisify(execFile)

/** Serialisable handle to our private tmux server — safe to send across the main↔host port. */
export interface TmuxRef {
  /** absolute path to the tmux binary */
  bin: string
  /** socket name passed as `-L` */
  socket: string
  /** path to our generated config passed as `-f` */
  conf: string
}

/** A {@link TmuxRef} plus the env to run tmux with (composed login-shell env → real PATH). */
export interface TmuxCtx extends TmuxRef {
  env: NodeJS.ProcessEnv
}

/**
 * Our minimal tmux config — tmux should be *invisible*: it's a persistence layer, not a UI.
 * No status bar (no wasted row), no prefix key (Ctrl-B etc. pass straight through to the shell
 * / agent — the app provides its own tabs & splits), sane sizing so reattaching at a different
 * window size reflows correctly, and a big scrollback.
 */
export function buildConf(shell: string): string {
  return [
    '# Generated by CmdrZone — durable terminal sessions. Safe to delete; it is recreated.',
    'set -g status off',
    'set -g prefix None',
    'set -g prefix2 None',
    'set -g mouse on',
    'set -g set-clipboard on',
    'set -g history-limit 50000',
    'set -g escape-time 10',
    'set -g focus-events on',
    'setw -g aggressive-resize on',
    'set -g window-size latest',
    'set -g default-terminal "tmux-256color"',
    'set -ga terminal-overrides ",*256col*:Tc"',
    `set -g default-shell "${shell}"`,
    ''
  ].join('\n')
}

/** Base args that target our private server + config: `tmux -L <socket> -f <conf> …`. */
export function baseArgs(ctx: TmuxCtx): string[] {
  return ['-L', ctx.socket, '-f', ctx.conf]
}

/**
 * Build the argv to attach-or-create a session. `-A` = attach if it exists, else create
 * (the whole durability primitive). When seeding a fresh session with a direct command
 * (spawn mode), the argv after `--` reaches the process exactly — multi-line safe, no shell.
 */
export function newSessionArgs(
  ctx: TmuxCtx,
  name: string,
  cols: number,
  rows: number,
  spawn?: { command: string; args: string[] }
): string[] {
  const args = [
    ...baseArgs(ctx),
    'new-session',
    '-A',
    '-s',
    name,
    '-x',
    String(Math.max(1, cols)),
    '-y',
    String(Math.max(1, rows))
  ]
  if (spawn) args.push('--', spawn.command, ...spawn.args)
  return args
}

async function run(ctx: TmuxCtx, args: string[]): Promise<{ ok: boolean; stdout: string }> {
  try {
    const { stdout } = await pexec(ctx.bin, [...baseArgs(ctx), ...args], {
      env: ctx.env,
      timeout: 5000
    })
    return { ok: true, stdout }
  } catch {
    return { ok: false, stdout: '' }
  }
}

/** Live session names on our server (empty if the server isn't running yet). */
export async function listSessions(ctx: TmuxCtx): Promise<string[]> {
  const { ok, stdout } = await run(ctx, ['list-sessions', '-F', '#{session_name}'])
  if (!ok) return []
  return stdout.split('\n').map((s) => s.trim()).filter(Boolean)
}

/** True if a session with this name already exists (used to skip re-seeding on reattach). */
export async function hasSession(ctx: TmuxCtx, name: string): Promise<boolean> {
  return (await run(ctx, ['has-session', '-t', name])).ok
}

/** Destroy a session for good (user closed the tab). Idempotent — missing sessions are fine. */
export async function killSession(ctx: TmuxCtx, name: string): Promise<void> {
  await run(ctx, ['kill-session', '-t', name])
}

/**
 * Type a line into a session's pane (literal, then Enter). Used to seed an interactive shell
 * with an agent-launch command — reliable regardless of client attach state, unlike raw writes.
 */
export async function sendKeys(ctx: TmuxCtx, name: string, line: string): Promise<void> {
  await run(ctx, ['send-keys', '-t', name, '-l', line])
  await run(ctx, ['send-keys', '-t', name, 'Enter'])
}
